version: "3"

services:
  archive_node:
    image: sportchain-node
    container_name: sportchain-archive-node
    restart: always
    command: >
      --chain dev
      --name "dev-archive"
      --port 30333
      --rpc-port 9944
      --unsafe-rpc-external
      --prometheus-external
      --node-key 0000000000000000000000000000000000000000000000000000000000000001
      --rpc-cors all
      --state-pruning archive
    ports:
      # - "0.0.0.0:30333:30333/tcp"
      - "0.0.0.0:9944:9944/tcp"
      # - "127.0.0.1:9615:9615/tcp"
    networks:
      - sportchain-node-network

  validator_1:
    image: sportchain-node
    container_name: sportchain-validator-1
    restart: always
    depends_on:
      - archive_node
    command: >
      --chain dev
      --base-path /chain-data/alice
      --alice
      --validator
      --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
    networks:
      - sportchain-node-network

  validator_2:
    image: sportchain-node
    container_name: sportchain-validator-2
    restart: always
    depends_on:
      - archive_node
    command: >
      --chain dev
      --base-path /chain-data/bob
      --bob
      --validator
      --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
    networks:
      - sportchain-node-network

  explorer:
    image: sportchain-explorer
    container_name: sportchain-explorer
    restart: always
    depends_on:
      - archive_node
    ports:
      - "0.0.0.0:80:80/tcp"
    networks:
      - sportchain-node-network

networks:
  sportchain-node-network:
    name: sportchain-node
