//! Autogenerated weights for `pallet_faucet`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-12, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `admin`, CPU: `<UNKNOWN>`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/gafi-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution
// compiled
// --pallet
// pallet_faucet
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./benchmarking/pallet-faucet/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_faucet.
pub trait WeightInfo {
    #[allow(missing_docs)]
    fn request_funds() -> Weight;
}

/// Weights for pallet_faucet using the Substrate node and recommended hardware.
pub struct FaucetWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for FaucetWeight<T> {
    fn request_funds() -> Weight {
        Weight::zero()
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn request_funds() -> Weight {
        Weight::zero()
    }
}
