name: Build and Release Devnet

on:
  workflow_dispatch:
  push:
    branches: [ "testnet" ]

jobs:
  deploy_image:

    environment: testnet

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to docker hub
      run: docker login -u atletanetwork -p ${{ secrets.REGISTRYPASS }} docker.io
      
    - name: Set timestamp variables
      run: |
          DATE=$(date +%d%m%y)
          HMS=$(date +%H%M%S)
          echo "DATE: $DATE, HMS: $HMS"

    - name: Build and push docker image
      run: |
          docker build --build-arg BUILD_FEATURES=fast-runtime -t docker.io/atletanetwork/atleta-node:testnet-${DATE}-${HMS} .
          docker tag docker.io/atletanetwork/atleta-node:testnet-${DATE}-${HMS} docker.io/atletanetwork/atleta-node:testnet-latest
          docker push docker.io/atletanetwork/atleta-node:testnet-${DATE}-${HMS}
          docker push docker.io/atletanetwork/atleta-node:testnet-latest
