name: Pull Request Title Check
permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate-pull-request-title:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get PR Branch Name
        id: pr_branch
        run: echo "::set-output name=PR_BRANCH::${GITHUB_REF#refs/heads/}"

      - name: Checkout PR Branch
        run: git checkout ${{ steps.pr_branch.outputs.PR_BRANCH }}



      - name: Validate Pull Request Title
        run: |
          PR_TITLE=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")
          # Check if the pull request title matches the required format
          if ! echo "$PR_TITLE" | grep -qE '^(Added|Changed|Deprecated|Removed|Fixed|Security): .+$'; then
            echo "Pull request title '$PR_TITLE' does not match the required format."
            echo "::error::Pull request title does not match the required format."
            exit 1
          fi 

      - name: Extract Changelog Entry
        id: extract_changelog_entry
        run: |
          PR_TITLE=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")
          CATEGORY=$(echo "$PR_TITLE" | cut -d ':' -f 1)
          CONTENT=$(echo "$PR_TITLE" | cut -d ':' -f 2-)
          CHANGELOG_ENTRY="**${CATEGORY}**\n${CONTENT}"

      - name: Update Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        if: success()
        run: |
          # Update changelog file
          sed -i "1s/^/${CHANGELOG_ENTRY}\n\n/" Changelog.md
          # Commit and push changelog update
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Changelog.md
          git commit -m "Update Changelog with changes from pull request #$PR_NUMBER"
          git push origin HEAD
