name: Deploy Explorer

on:
  push:
    branches: [ "devnet" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"


    - name: Create Image Tarball for Explorer
      run: |
        cd polkadot-js-apps
        docker build -t sportchain-explorer -f docker/Dockerfile .
        docker save -o sportchain-explorer.tar sportchain-explorer
        mv sportchain-explorer.tar ./artifacts

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.EXPLORER_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.EXPLORER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Copy Files to Server
      run: |
        scp -r artifacts/sportchain-explorer.tar ${{ secrets.EXPLORER_USERNAME}}@${{ secrets.EXPLORER_HOST }}:/sportchain/

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EXPLORER_HOST }}
        username: ${{ secrets.EXPLORER_USERNAME }}
        key: ${{ secrets.EXPLORER_PRIVATE_KEY }}
        script: |
          cd /sportchain 
          docker load -i sportchain-explorer.tar
          docker run -p 80:80/tcp sportchain-explorer
