name: Release Atleta Node bins

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
  push:
    branches:
      - testnet
      - devnet

permissions:
  contents: write

jobs:
  linux_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler

      - run: cargo build --locked --release

      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}-release-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          make_latest: true
          files: |
            LICENSE
            ./target/release/atleta-node

  macos_release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - run: |
          brew update
          brew install protobuf

      - run: cargo build --locked --release

      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}-release-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          make_latest: true
          files: |
            LICENSE
            ./target/release/atleta-node

