name: Release Atleta Node bins

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-v*'

permissions:
  contents: write

jobs:
  define_vars:
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.vars.outputs.release_name }}
      commit_sha: ${{ steps.vars.outputs.commit_sha }}
    steps:
      - id: vars
        run: |
          commit_sha=${{ github.sha }}
          echo "commit_sha=${commit_sha:0:7}" >> "$GITHUB_OUTPUT"
          echo "release_name=$(echo ${{ github.ref_name }} | sed 's/^release-//')" >> "$GITHUB_OUTPUT"

  linux_release:
    runs-on: ubuntu-latest
    needs: define_vars

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler

      - run: cargo build --locked --release

      - uses: softprops/action-gh-release@v2
        env:
          release_name: ${{ needs.define_vars.outputs.release_name }}
          commit_sha: ${{ needs.define_vars.outputs.commit_sha }}
        with:
          name: release-${{ env.release_name }}-${{ env.commit_sha }}-${{ runner.os }}-${{ runner.arch }}
          make_latest: true
          files: |
            LICENSE
            ./target/release/atleta-node

  macos_release:
    runs-on: macos-latest
    needs: define_vars

    steps:
      - uses: actions/checkout@v4
      - run: |
          brew update
          brew upgrade rustup
          brew install protobuf
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - run: cargo build --locked --release

      - uses: softprops/action-gh-release@v2
        env:
          release_name: ${{ needs.define_vars.outputs.release_name }}
          commit_sha: ${{ needs.define_vars.outputs.commit_sha }}
        with:
          name: release-${{ env.release_name }}-${{ env.commit_sha }}-${{ runner.os }}-${{ runner.arch }}
          make_latest: true
          files: |
            LICENSE
            ./target/release/atleta-node

